openapi: 3.0.0
info:
  title: Bütçe Yönetim Sistemi API
  version: 1.0.0
  description: Bütçe Yönetim Sistemi için REST API dokümantasyonu

servers:
  - url: /api
    description: API endpoint

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: PHPSESSID

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

paths:
  /auth.php:
    post:
      tags: [Kimlik Doğrulama]
      summary: Kullanıcı girişi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - action
                - username
                - password
              properties:
                action:
                  type: string
                  enum: [login]
                username:
                  type: string
                password:
                  type: string
                remember:
                  type: boolean
      responses:
        200:
          description: Başarılı giriş
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        401:
          description: Hatalı kimlik bilgileri
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags: [Kimlik Doğrulama]
      summary: Kullanıcı çıkışı
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - action
              properties:
                action:
                  type: string
                  enum: [logout]
      responses:
        200:
          description: Başarılı çıkış
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"

  /income.php:
    get:
      tags: [Gelir Yönetimi]
      summary: Gelirleri listele
      security:
        - sessionAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: Gelir listesi
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    amount:
                      type: number
                    currency:
                      type: string
                    date:
                      type: string
                      format: date
                    status:
                      type: string
                      enum: [pending, received]

    post:
      tags: [Gelir Yönetimi]
      summary: Yeni gelir ekle
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - amount
                - currency
                - date
              properties:
                name:
                  type: string
                amount:
                  type: number
                currency:
                  type: string
                date:
                  type: string
                  format: date
                frequency:
                  type: string
                  enum: [once, daily, weekly, monthly, yearly]
                end_date:
                  type: string
                  format: date
      responses:
        201:
          description: Gelir eklendi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"

  /payments.php:
    get:
      tags: [Ödeme Yönetimi]
      summary: Ödemeleri listele
      security:
        - sessionAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: Ödeme listesi
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    amount:
                      type: number
                    currency:
                      type: string
                    date:
                      type: string
                      format: date
                    status:
                      type: string
                      enum: [pending, paid]

    post:
      tags: [Ödeme Yönetimi]
      summary: Yeni ödeme ekle
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - amount
                - currency
                - date
              properties:
                name:
                  type: string
                amount:
                  type: number
                currency:
                  type: string
                date:
                  type: string
                  format: date
                frequency:
                  type: string
                  enum: [once, daily, weekly, monthly, yearly]
                end_date:
                  type: string
                  format: date
      responses:
        201:
          description: Ödeme eklendi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"

  /savings.php:
    get:
      tags: [Tasarruf Yönetimi]
      summary: Tasarrufları listele
      security:
        - sessionAuth: []
      responses:
        200:
          description: Tasarruf listesi
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    target_amount:
                      type: number
                    current_amount:
                      type: number
                    currency:
                      type: string
                    start_date:
                      type: string
                      format: date
                    target_date:
                      type: string
                      format: date

    post:
      tags: [Tasarruf Yönetimi]
      summary: Yeni tasarruf ekle
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - target_amount
                - currency
                - start_date
                - target_date
              properties:
                name:
                  type: string
                target_amount:
                  type: number
                current_amount:
                  type: number
                  default: 0
                currency:
                  type: string
                start_date:
                  type: string
                  format: date
                target_date:
                  type: string
                  format: date
      responses:
        201:
          description: Tasarruf eklendi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"

  /currency.php:
    get:
      tags: [Döviz İşlemleri]
      summary: Döviz kuru bilgisi al
      security:
        - sessionAuth: []
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: to
          in: query
          required: true
          schema:
            type: string
        - name: date
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: Döviz kuru
          content:
            application/json:
              schema:
                type: object
                properties:
                  rate:
                    type: number
                  date:
                    type: string
                    format: date

  /summary.php:
    get:
      tags: [Özet Raporlar]
      summary: Finansal özet bilgileri
      security:
        - sessionAuth: []
      parameters:
        - name: month
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: Özet bilgiler
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_income:
                    type: number
                  total_expenses:
                    type: number
                  net_balance:
                    type: number
                  currency:
                    type: string
                  period:
                    type: string
                    format: date

  /user.php:
    put:
      tags: [Kullanıcı Yönetimi]
      summary: Kullanıcı ayarlarını güncelle
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_currency:
                  type: string
                theme:
                  type: string
                  enum: [light, dark, system]
      responses:
        200:
          description: Ayarlar güncellendi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
